### ISSUE TITLE
Cannot run script

### ISSUE THREAD

**Issue by andrii-lisovskiy** [OlegTsib/Xcode-Accessibility-Identifier#1]
Hi, just found your awesome scripts, really need to automate adding of accessibilityIds.
But when I am running it on my mac OS Big Sur 11.4 () - I receive error:

```
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    with ThreadPoolExecutor(max_workers=len(ui_files_path)) as executor:
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 129, in __init__
    raise ValueError("max_workers must be greater than 0")
ValueError: max_workers must be greater than 0
```

python --version
Python 2.7.16

python3 --version
Python 3.7.3

Can you please help?

**Comment by andrii-lisovskiy** [comment]
Looks like there was a problem with backslash before spaces and ampersands. Now it works, thank you!
